Signals are used to communicate between process and os.
When executing the program and the os detects any serious error it sends signal to the
process and may not execute anymore.
Process can have handlers for before exiting the process perform some activities.

Interrupts vs signal
    Interrupts are generated by the process, handled by the kernel
    Signal are generated by kernal and handled by process.
Error signals generally causes termination of the program.

SIGFPE  -   Arithmetic Errors.
SIGILL  -   Illegal instructions
SIGSEGV -   Process tries to access memory location not allocated to it. //Segmentaion fault.
SIGBUS  -   Memory location accessed does not exist.
SIGABRT -   standard library to report internal error.assert()
SIGSYS  -   invalid argument sent to system call
SIGTRAP -   Exception occoured.//Example when a variable changes value this will get triggered.
